// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// PyTorchJobListerExpansion allows custom methods to be added to
// PyTorchJobLister.
type PyTorchJobListerExpansion interface{}

// PyTorchJobNamespaceListerExpansion allows custom methods to be added to
// PyTorchJobNamespaceLister.
type PyTorchJobNamespaceListerExpansion interface{}

// TFJobListerExpansion allows custom methods to be added to
// TFJobLister.
type TFJobListerExpansion interface{}

// TFJobNamespaceListerExpansion allows custom methods to be added to
// TFJobNamespaceLister.
type TFJobNamespaceListerExpansion interface{}
