// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/ankushagarwal/kf-training-controller/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeflowV1alpha2 struct {
	*testing.Fake
}

func (c *FakeKubeflowV1alpha2) TFJobs(namespace string) v1alpha2.TFJobInterface {
	return &FakeTFJobs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeflowV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
