// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/ankushagarwal/kf-training-controller/pkg/apis/kubeflow/v1alpha2"
	scheme "github.com/ankushagarwal/kf-training-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PyTorchJobsGetter has a method to return a PyTorchJobInterface.
// A group's client should implement this interface.
type PyTorchJobsGetter interface {
	PyTorchJobs(namespace string) PyTorchJobInterface
}

// PyTorchJobInterface has methods to work with PyTorchJob resources.
type PyTorchJobInterface interface {
	Create(*v1alpha2.PyTorchJob) (*v1alpha2.PyTorchJob, error)
	Update(*v1alpha2.PyTorchJob) (*v1alpha2.PyTorchJob, error)
	UpdateStatus(*v1alpha2.PyTorchJob) (*v1alpha2.PyTorchJob, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.PyTorchJob, error)
	List(opts v1.ListOptions) (*v1alpha2.PyTorchJobList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.PyTorchJob, err error)
	PyTorchJobExpansion
}

// pyTorchJobs implements PyTorchJobInterface
type pyTorchJobs struct {
	client rest.Interface
	ns     string
}

// newPyTorchJobs returns a PyTorchJobs
func newPyTorchJobs(c *KubeflowV1alpha2Client, namespace string) *pyTorchJobs {
	return &pyTorchJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pyTorchJob, and returns the corresponding pyTorchJob object, and an error if there is any.
func (c *pyTorchJobs) Get(name string, options v1.GetOptions) (result *v1alpha2.PyTorchJob, err error) {
	result = &v1alpha2.PyTorchJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pytorchjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PyTorchJobs that match those selectors.
func (c *pyTorchJobs) List(opts v1.ListOptions) (result *v1alpha2.PyTorchJobList, err error) {
	result = &v1alpha2.PyTorchJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pytorchjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pyTorchJobs.
func (c *pyTorchJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pytorchjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a pyTorchJob and creates it.  Returns the server's representation of the pyTorchJob, and an error, if there is any.
func (c *pyTorchJobs) Create(pyTorchJob *v1alpha2.PyTorchJob) (result *v1alpha2.PyTorchJob, err error) {
	result = &v1alpha2.PyTorchJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pytorchjobs").
		Body(pyTorchJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pyTorchJob and updates it. Returns the server's representation of the pyTorchJob, and an error, if there is any.
func (c *pyTorchJobs) Update(pyTorchJob *v1alpha2.PyTorchJob) (result *v1alpha2.PyTorchJob, err error) {
	result = &v1alpha2.PyTorchJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pytorchjobs").
		Name(pyTorchJob.Name).
		Body(pyTorchJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *pyTorchJobs) UpdateStatus(pyTorchJob *v1alpha2.PyTorchJob) (result *v1alpha2.PyTorchJob, err error) {
	result = &v1alpha2.PyTorchJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pytorchjobs").
		Name(pyTorchJob.Name).
		SubResource("status").
		Body(pyTorchJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the pyTorchJob and deletes it. Returns an error if one occurs.
func (c *pyTorchJobs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pytorchjobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pyTorchJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pytorchjobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pyTorchJob.
func (c *pyTorchJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.PyTorchJob, err error) {
	result = &v1alpha2.PyTorchJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pytorchjobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
